"""Generate a starter rule spec from the manufacturer Excel templates.

The ``Performance`` sheet of the params workbook has clean MIN/MAX columns per
parameter — ideal source material for ``range`` rules. The ``aliases`` sheet
maps internal names to log keys. This module turns those into a YAML spec the
engine can consume, which a human then reviews and trims.

Usage::

    python -m loginspect.specgen \\
        --params params_GCU-P.xlsm --washtable washtable_GCU-P.xlsx \\
        --out specs/gcu_p.generated.yaml

This is intentionally conservative: it emits rules it is confident about and
records everything else as comments so a reviewer can promote them by hand.
"""

from __future__ import annotations

import argparse
import re
from typing import Any

try:
    from openpyxl import load_workbook
except ImportError:  # pragma: no cover
    load_workbook = None  # type: ignore

import yaml


def _norm_key(name: str) -> str:
    """Best-effort mapping of a spec parameter name to a log key."""
    return re.sub(r"[^a-z0-9]+", "_", str(name).strip().lower()).strip("_")


def rules_from_performance(path: str) -> list[dict[str, Any]]:
    """Build range rules from the Performance sheet's MIN/MAX columns."""
    if load_workbook is None:
        raise RuntimeError("openpyxl is required for spec generation.")
    wb = load_workbook(path, data_only=True, read_only=True)
    if "Performance" not in wb.sheetnames:
        return []
    ws = wb["Performance"]
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return []
    header = [str(c).strip() if c is not None else "" for c in rows[0]]
    try:
        i_param = header.index("PARAMETER")
        i_min = header.index("MIN")
        i_max = header.index("MAX")
    except ValueError:
        return []

    rules: list[dict[str, Any]] = []
    for row in rows[1:]:
        param = row[i_param] if i_param < len(row) else None
        lo = row[i_min] if i_min < len(row) else None
        hi = row[i_max] if i_max < len(row) else None
        if not param or (lo is None and hi is None):
            continue
        rules.append(
            {
                "id": f"perf_{_norm_key(param)}",
                "check": "range",
                "key": _norm_key(param),
                "severity": "warning",
                "description": f"Performance limit for {param}",
                "enabled": False,  # reviewer must map key + enable
                "params": {"min": lo, "max": hi},
            }
        )
    wb.close()
    return rules


def baseline_rules() -> list[dict[str, Any]]:
    """Hand-curated rules that apply to this device family regardless of Excel."""
    return [
        {
            "id": "service_status_error",
            "check": "forbidden_value",
            "key": "service_status",
            "severity": "error",
            "description": "Service status should not report ERROR.",
            "params": {"values": ["ERROR", "FAULT"]},
        },
        {
            "id": "bldc_active_faults",
            "check": "forbidden_value",
            "key": "bldc_status_stmcsdk_faults_active",
            "severity": "error",
            "description": "Active motor-controller faults indicate a problem.",
            "params": {"values": ["UNDER_VOLT", "OVER_VOLT", "OVER_CURRENT",
                                   "OVER_TEMP", "START_UP", "SPEED_FDBK"]},
        },
        {
            "id": "veeprom_errors",
            "check": "nonzero_counter",
            "key": "veeprom_error_cntr",
            "severity": "error",
            "description": "EEPROM error counter must stay at zero.",
            "params": {"threshold": 0},
        },
        {
            "id": "persist_data_errors",
            "check": "nonzero_counter",
            "key": "persist_data_error_cntr",
            "severity": "error",
            "description": "Persistent-data error counter must stay at zero.",
            "params": {"threshold": 0},
        },
    ]


def build_spec(params_path: str | None, washtable_path: str | None) -> dict[str, Any]:
    rules = baseline_rules()
    if params_path:
        rules.extend(rules_from_performance(params_path))
    return {
        "name": "gcu-p-generated",
        "version": "0.1",
        "rules": rules,
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate a rule spec from Excel templates.")
    ap.add_argument("--params", help="params_*.xlsm workbook")
    ap.add_argument("--washtable", help="washtable_*.xlsx workbook")
    ap.add_argument("--out", required=True, help="output YAML path")
    args = ap.parse_args(argv)

    spec = build_spec(args.params, args.washtable)
    header = (
        "# Auto-generated by loginspect.specgen — REVIEW BEFORE USE.\n"
        "# Rules with 'enabled: false' need a verified key mapping first.\n"
    )
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(header)
        yaml.safe_dump(spec, fh, sort_keys=False, allow_unicode=True)
    n = len(spec["rules"])
    print(f"Wrote {n} rules to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
